// Request context — flows the per-request id + user id through async
// work without changing function signatures. Mirrors the TenantContext
// pattern in src/tenancy so the JSON logger can pick up both contexts
// from one place.
//
// Why AsyncLocalStorage:
//   • Request handlers fan out across awaits, promises, and timers; a
//     thread-local works for the entire chain without manual plumbing.
//   • The logger (src/utils/logger.ts) reads from this storage on every
//     log line, so a deeply-nested business call still emits a record
//     tagged with the originating request id and user.
//
// What's in the context:
//   • requestId — UUIDv4 string, generated by middleware when no
//     X-Request-Id header is present. Echoed back on the response.
//   • userId    — authenticated subject, when known. The auth
//     middleware sets it after JWT/API-key resolution.
//   • method/path — convenience copies of the request line so log
//     handlers don't have to re-derive them.

import { AsyncLocalStorage } from 'async_hooks';
import crypto from 'crypto';

export interface RequestContext {
  requestId: string;
  userId?: string;
  method?: string;
  path?: string;
  /** Stable timestamp for the request start (ms since epoch). The HTTP
   *  log middleware uses this so durations stay accurate even when the
   *  handler reads the context late. */
  startMs?: number;
}

const storage = new AsyncLocalStorage<RequestContext>();

/** Generate a new request id. Uses crypto.randomUUID() when available
 *  (Node 14.17+) and falls back to a 32-char hex token. */
export function newRequestId(): string {
  try {
    if (typeof (crypto as any).randomUUID === 'function') {
      return (crypto as any).randomUUID();
    }
  } catch { /* fall through */ }
  return crypto.randomBytes(16).toString('hex');
}

/** Run a callback inside the request scope. Nests cleanly with the
 *  tenant scope — both AsyncLocalStorages are independent. */
export function runWithRequest<T>(ctx: RequestContext, fn: () => T): T {
  return storage.run(ctx, fn);
}

/** Read the active request context, if any. Returns undefined when
 *  called outside any request — bootstrap / scheduler / background
 *  work. The logger handles the undefined case by simply not emitting
 *  the request fields. */
export function getCurrentRequest(): RequestContext | undefined {
  return storage.getStore();
}

/** Convenience: just the id, with no fallback. */
export function getCurrentRequestId(): string | undefined {
  return storage.getStore()?.requestId;
}

/** Mutate the current request context. Used by the auth middleware to
 *  back-fill `userId` once the JWT has been verified. No-op when
 *  there's no active scope (defensive — the caller shouldn't have
 *  called this outside a request, but we don't want to throw). */
export function setCurrentUserId(userId: string | undefined): void {
  const ctx = storage.getStore();
  if (!ctx) return;
  ctx.userId = userId;
}

/** Convert the active context into log fields. Returns an empty object
 *  outside any scope so the logger can spread it unconditionally. */
export function requestLogFields(): Record<string, string | number> {
  const ctx = storage.getStore();
  if (!ctx) return {};
  const out: Record<string, string | number> = { requestId: ctx.requestId };
  if (ctx.userId) out.userId = ctx.userId;
  return out;
}
