// Deterministic code generation for the Self-Development SDK.
//
// Two surfaces:
//   generateSkillFiles(spec) → FileChange[] for a fresh skill
//                              (TS source, registry hint, sandbox-safe
//                               .plugin.js for hot reload)
//   generateWorkflowFile(spec) → FileChange for a WorkflowDef JSON
//
// We don't call out to an LLM here. The templates are well-known
// shapes the existing skill catalogue already proved out, and a
// follow-up commit can graft an LLM polish pass in front of these
// without changing the contract.
//
// The plugin-shaped output (a single .plugin.js dropped under
// SKILL_PLUGIN_DIR) is what the platform's hot-reload loader picks
// up at runtime. That's the seam an agent uses to ship a working
// skill into a running process; the matching .ts source lives next
// to the in-tree skill catalogue so the next deploy bakes it in.

import path from 'path';
import type {
  FileChange,
  SkillSpec,
  SkillParam,
  WorkflowSpec,
  TestCase,
} from './SdkTypes.js';

/** Where dropped-in plugin files live by convention. The runtime
 *  reads this from SKILL_PLUGIN_DIR; tests + planning callers pass
 *  the same path so the FileChange paths line up. */
export const DEFAULT_PLUGIN_DIR = 'src/skills/generated/plugins';

/** In-tree source location for skills the SDK has emitted. The next
 *  deploy bakes them in alongside the rest of the catalogue. */
export const DEFAULT_SKILL_SOURCE_DIR = 'src/skills/generated';

export interface GenerateSkillOptions {
  /** Override the default in-tree directory. */
  sourceDir?: string;
  /** Override the default plugin directory. */
  pluginDir?: string;
}

export function generateSkillFiles(spec: SkillSpec, opts: GenerateSkillOptions = {}): FileChange[] {
  validateSkillSpec(spec);
  const sourceDir = opts.sourceDir ?? DEFAULT_SKILL_SOURCE_DIR;
  const pluginDir = opts.pluginDir ?? DEFAULT_PLUGIN_DIR;

  const className = pascalCase(spec.id) + 'Skill';
  const handlerName = camelCase(spec.id) + 'Run';
  const fileBase    = kebabCase(spec.id);

  return [
    {
      path: posix(path.join(sourceDir, `${fileBase}.ts`)),
      mode: 'add',
      contents: renderSkillSource(spec, className, handlerName),
    },
    {
      path: posix(path.join(pluginDir, `${fileBase}.plugin.js`)),
      mode: 'add',
      contents: renderPluginShim(spec, handlerName),
    },
  ];
}

export function generateWorkflowFile(
  spec: WorkflowSpec,
  opts: { workflowDir?: string } = {},
): FileChange {
  validateWorkflowSpec(spec);
  const workflowDir = opts.workflowDir ?? 'src/runbooks/library';
  return {
    path: posix(path.join(workflowDir, `${kebabCase(spec.id)}.workflow.json`)),
    mode: 'add',
    contents: JSON.stringify({
      schemaVersion: 1,
      id: spec.id,
      name: spec.name,
      description: spec.description ?? '',
      version: spec.version ?? '1.0.0',
      tags: spec.tags ?? [],
      inputs: (spec.inputs ?? []).map(i => ({
        name: i.name, type: i.type,
        description: i.description, required: i.required ?? false,
      })),
      onError: 'fail',
      steps: spec.steps,
    }, null, 2) + '\n',
  };
}

/** Default tests the SDK runs against a generated skill if the caller
 *  didn't supply their own. Each command gets a smoke test that just
 *  asserts the handler returns ok=true (no params other than what the
 *  spec marks required). */
export function defaultSkillTests(spec: SkillSpec): TestCase[] {
  const baseParams: Record<string, unknown> = {};
  for (const p of spec.parameters) {
    if (p.required && p.example !== undefined) baseParams[p.name] = p.example;
    else if (p.required) baseParams[p.name] = exampleFor(p);
  }
  return spec.commands.map((_cmd, i) => ({
    name: `${spec.id} smoke #${i + 1}`,
    command: `${spec.id}.run`,
    params: baseParams,
    expect: { ok: true },
  }));
}

// ─── Templates ────────────────────────────────────────────────────────

function renderSkillSource(spec: SkillSpec, className: string, handlerName: string): string {
  const params = spec.parameters;
  const tagsLine = (spec.tags ?? []).join(', ');
  const lines: string[] = [];

  // Banner comment.
  lines.push(`// ${spec.name}`);
  lines.push(`//`);
  lines.push(`// ${spec.description}`);
  if (spec.logic) {
    lines.push(`//`);
    spec.logic.split('\n').forEach(l => lines.push(`// ${l}`));
  }
  lines.push(`//`);
  lines.push(`// Auto-generated by the Self-Development SDK.`);
  if (tagsLine) lines.push(`// Tags: ${tagsLine}`);
  lines.push(``);

  // Imports — small, stable surface; matches the in-tree skill style.
  lines.push(`import type { Skill } from '../../types/index.js';`);
  lines.push(`import { encode, ok, fail } from '../SkillResult.js';`);
  lines.push(`import { exec } from 'child_process';`);
  lines.push(`import { promisify } from 'util';`);
  lines.push(`import { shellEscape } from '../../utils/shellEscape.js';`);
  lines.push(``);
  lines.push(`const execAsync = promisify(exec);`);
  lines.push(``);

  // Skill class.
  lines.push(`export class ${className} {`);
  lines.push(`  getSkill(): Skill {`);
  lines.push(`    return {`);
  lines.push(`      id: '${spec.id}',`);
  lines.push(`      name: ${stringLit(spec.name)},`);
  lines.push(`      description: ${stringLit(spec.description)},`);
  lines.push(`      category: '${spec.category ?? 'general'}',`);
  lines.push(`      enabled: true,`);
  lines.push(`      commands: [{`);
  lines.push(`        name: '${spec.id}.run',`);
  lines.push(`        description: ${stringLit(spec.description)},`);
  lines.push(`        handler: '${handlerName}',`);
  lines.push(`        parameters: ${renderParameters(params)},`);
  lines.push(`      }],`);
  lines.push(`    };`);
  lines.push(`  }`);
  lines.push(``);
  lines.push(`  async ${handlerName}(params: Record<string, unknown>): Promise<string> {`);
  // Param destructuring with required-field validation.
  for (const p of params) {
    lines.push(`    const ${p.name} = params['${p.name}'] as ${tsTypeOf(p)};`);
    if (p.required) {
      lines.push(`    if (${p.name} === undefined || ${p.name} === null${p.type === 'string' ? ` || ${p.name} === ''` : ''}) {`);
      lines.push(`      return encode(fail('${p.name} is required'));`);
      lines.push(`    }`);
    }
  }
  lines.push(``);
  lines.push(`    try {`);
  // For each command, do shell-escape substitution + run via execAsync.
  for (let i = 0; i < spec.commands.length; i++) {
    const cmdLit = renderCommandTemplate(spec.commands[i], params);
    lines.push(`      const result${i} = await execAsync(${cmdLit}, { timeout: 30_000 });`);
  }
  lines.push(`      return encode(ok({`);
  for (let i = 0; i < spec.commands.length; i++) {
    lines.push(`        step${i + 1}: result${i}.stdout.toString().trim(),`);
  }
  lines.push(`      }, '${spec.name} completed'));`);
  lines.push(`    } catch (err: unknown) {`);
  lines.push(`      const e = err as { stderr?: { toString(): string }; message?: string };`);
  lines.push(`      const msg = e.stderr?.toString().trim() || e.message || String(err);`);
  lines.push(`      return encode(fail(msg, '${spec.name} failed'));`);
  lines.push(`    }`);
  lines.push(`  }`);
  lines.push(`}`);
  lines.push(``);

  return lines.join('\n');
}

/** Plugin-shape ESM module that exposes a default { skill, executor }
 *  pair so SkillPluginLoader picks it up at runtime via fs.watch.
 *  Each command body re-uses the same exec pipeline but inline so the
 *  plugin doesn't depend on any compiled source. */
function renderPluginShim(spec: SkillSpec, handlerName: string): string {
  const lines: string[] = [];
  lines.push(`// ${spec.name} (plugin shim)`);
  lines.push(`// Auto-generated by the Self-Development SDK. Drop into SKILL_PLUGIN_DIR`);
  lines.push(`// for hot reload; the in-tree TS source ships in the next deploy.`);
  lines.push(``);
  lines.push(`import { exec } from 'node:child_process';`);
  lines.push(`import { promisify } from 'node:util';`);
  lines.push(`const execAsync = promisify(exec);`);
  lines.push(``);
  lines.push(`function shellEscape(value) {`);
  lines.push(`  if (typeof value !== 'string') value = String(value ?? '');`);
  lines.push(`  if (/^[A-Za-z0-9_\\-./@:=+,]+$/.test(value)) return value;`);
  lines.push(`  return "'" + value.replace(/'/g, "'\\\\''") + "'";`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`function ok(data, summary) { return JSON.stringify({ ok: true, summary, data }); }`);
  lines.push(`function fail(error, summary) { return JSON.stringify({ ok: false, summary: summary ?? error, error }); }`);
  lines.push(``);
  lines.push(`export default {`);
  lines.push(`  skill: {`);
  lines.push(`    id: '${spec.id}',`);
  lines.push(`    name: ${stringLit(spec.name)},`);
  lines.push(`    description: ${stringLit(spec.description)},`);
  lines.push(`    category: '${spec.category ?? 'general'}',`);
  lines.push(`    enabled: true,`);
  lines.push(`    commands: [{`);
  lines.push(`      name: '${spec.id}.run',`);
  lines.push(`      description: ${stringLit(spec.description)},`);
  lines.push(`      handler: '${handlerName}',`);
  lines.push(`    }],`);
  lines.push(`  },`);
  lines.push(`  executor: {`);
  lines.push(`    async ${handlerName}(params) {`);
  for (const p of spec.parameters) {
    if (p.required) {
      lines.push(`      if (params['${p.name}'] === undefined || params['${p.name}'] === null${p.type === 'string' ? ` || params['${p.name}'] === ''` : ''}) return fail('${p.name} is required');`);
    }
  }
  // Extract every parameter into a local — the rendered command literal
  // references each `name` directly via `${shellEscape(String(name))}`.
  for (const p of spec.parameters) {
    lines.push(`      const ${p.name} = params['${p.name}'];`);
  }
  lines.push(`      try {`);
  for (let i = 0; i < spec.commands.length; i++) {
    const cmdLit = renderCommandTemplate(spec.commands[i], spec.parameters);
    lines.push(`        const result${i} = await execAsync(${cmdLit}, { timeout: 30_000 });`);
  }
  lines.push(`        return ok({`);
  for (let i = 0; i < spec.commands.length; i++) {
    lines.push(`          step${i + 1}: result${i}.stdout.toString().trim(),`);
  }
  lines.push(`        }, '${spec.name} completed');`);
  lines.push(`      } catch (err) {`);
  lines.push(`        const msg = err?.stderr?.toString().trim() || err?.message || String(err);`);
  lines.push(`        return fail(msg, '${spec.name} failed');`);
  lines.push(`      }`);
  lines.push(`    },`);
  lines.push(`  },`);
  lines.push(`};`);
  lines.push(``);
  return lines.join('\n');
}

// ─── helpers ──────────────────────────────────────────────────────────

/** Build a JS template-literal expression for a command body that
 *  shell-escapes any {{paramName}} substitution. We treat {{name}}
 *  verbatim if `name` isn't a declared parameter so operators can
 *  reference env-style placeholders without triggering an error. */
function renderCommandTemplate(template: string, params: SkillParam[]): string {
  const knownParams = new Set(params.map(p => p.name));
  // Split into literal + substitution segments.
  const segments: string[] = [];
  const re = /\{\{\s*([A-Za-z_][A-Za-z0-9_]*)\s*\}\}/g;
  let lastIndex = 0;
  let m: RegExpExecArray | null;
  while ((m = re.exec(template))) {
    if (m.index > lastIndex) segments.push(escapeForTemplateLiteral(template.slice(lastIndex, m.index)));
    if (knownParams.has(m[1])) segments.push('${shellEscape(String(' + m[1] + '))}');
    else segments.push('${' + JSON.stringify('{{' + m[1] + '}}') + '}');
    lastIndex = m.index + m[0].length;
  }
  if (lastIndex < template.length) segments.push(escapeForTemplateLiteral(template.slice(lastIndex)));
  // Wrap in template-literal backticks. JSON-stringifying the literal
  // would over-quote `${...}` substitutions.
  return '`' + segments.join('') + '`';
}

function escapeForTemplateLiteral(text: string): string {
  return text.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

function renderParameters(params: SkillParam[]): string {
  const fields: Record<string, unknown> = {};
  for (const p of params) {
    fields[p.name] = {
      type: p.type,
      description: p.description ?? '',
      required: p.required ?? false,
    };
  }
  return JSON.stringify(fields, null, 2).replace(/\n/g, '\n        ');
}

function tsTypeOf(p: SkillParam): string {
  return p.type === 'string' ? 'string' : p.type === 'number' ? 'number' : 'boolean';
}

function stringLit(text: string): string {
  return JSON.stringify(text);
}

function exampleFor(p: SkillParam): unknown {
  switch (p.type) {
    case 'string':  return `example-${p.name}`;
    case 'number':  return 0;
    case 'boolean': return false;
  }
}

function pascalCase(text: string): string {
  return text.replace(/(^[a-z]|[._-][a-z])/g, m => m.replace(/[._-]/, '').toUpperCase());
}
function camelCase(text: string): string {
  const pc = pascalCase(text);
  return pc.charAt(0).toLowerCase() + pc.slice(1);
}
function kebabCase(text: string): string {
  return text.toLowerCase().replace(/[._]+/g, '-').replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');
}
function posix(p: string): string { return p.replace(/\\/g, '/'); }

// ─── validation ──────────────────────────────────────────────────────

function validateSkillSpec(spec: SkillSpec): void {
  if (!spec.id || !/^[a-z][a-zA-Z0-9_]*(\.[a-zA-Z][a-zA-Z0-9_]*)+$/.test(spec.id)) {
    throw new Error(`SkillSpec.id must be a dotted identifier starting with a lowercase letter ("monitor.diskCheck"), got "${spec.id}"`);
  }
  if (!spec.name)        throw new Error('SkillSpec.name is required');
  if (!spec.description) throw new Error('SkillSpec.description is required');
  if (!Array.isArray(spec.commands) || spec.commands.length === 0) {
    throw new Error('SkillSpec.commands must list at least one shell command');
  }
  const names = new Set<string>();
  for (const p of spec.parameters ?? []) {
    if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(p.name)) throw new Error(`bad parameter name: "${p.name}"`);
    if (names.has(p.name)) throw new Error(`duplicate parameter: "${p.name}"`);
    names.add(p.name);
  }
}

function validateWorkflowSpec(spec: WorkflowSpec): void {
  if (!spec.id) throw new Error('WorkflowSpec.id is required');
  if (!spec.name) throw new Error('WorkflowSpec.name is required');
  if (!Array.isArray(spec.steps) || spec.steps.length === 0) {
    throw new Error('WorkflowSpec.steps must list at least one step');
  }
}
